#redis
spring.redis:
  cluster:
    nodes: 10.12.3.125:7000,10.12.3.125:7001,10.12.3.125:7002
    max-redirects: 3
  password: cmopRedis
  timeout: 1000
  lettuce.pool:
    max-active: 2000  # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
    max-idle: 500  # 连接池中的最大空闲连接，默认值也是8。
    min-idle: 50  #连接池中的最小空闲连接，默认值也是0。
    max-wait: 1000  # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException  